apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekdays-fin-pods-scale-up
spec:
  schedule: "0 17 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: custom-metric-extporter
            image: asia-south1-docker.pkg.dev/icici-terraform-svc-now/gke-scheduled-autoscaler/custom-metric-exporter
            command:
              - /export
              - --name=scheduled_autoscaler
              - --value=70
          restartPolicy: OnFailure
      backoffLimit: 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekdays-fin-pods-scale-down
spec:
  schedule: "0 0 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: custom-metric-extporter
            image: asia-south1-docker.pkg.dev/icici-terraform-svc-now/gke-scheduled-autoscaler/custom-metric-exporter
            command:
              - /export
              - --name=scheduled_autoscaler
              - --value=35
          restartPolicy: OnFailure
      backoffLimit: 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekdays-nonfin-pods-scale-up
spec:
  schedule: "0 17 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: custom-metric-extporter
            image: asia-south1-docker.pkg.dev/icici-terraform-svc-now/gke-scheduled-autoscaler/custom-metric-exporter
            command:
              - /export
              - --name=scheduled_autoscaler
              - --value=40
          restartPolicy: OnFailure
      backoffLimit: 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekdays-nonfin-pods-scale-down
spec:
  schedule: "0 0 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: custom-metric-extporter
            image: asia-south1-docker.pkg.dev/icici-terraform-svc-now/gke-scheduled-autoscaler/custom-metric-exporter
            command:
              - /export
              - --name=scheduled_autoscaler
              - --value=20
          restartPolicy: OnFailure
      backoffLimit: 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekends-fin-pods-scale-up
spec:
  schedule: "0 14 * * 6,0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: custom-metric-extporter
            image: asia-south1-docker.pkg.dev/icici-terraform-svc-now/gke-scheduled-autoscaler/custom-metric-exporter
            command:
              - /export
              - --name=scheduled_autoscaler
              - --value=70
          restartPolicy: OnFailure
      backoffLimit: 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekends-fin-pods-scale-down
spec:
  schedule: "0 0 * * 6,0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: custom-metric-extporter
            image: asia-south1-docker.pkg.dev/icici-terraform-svc-now/gke-scheduled-autoscaler/custom-metric-exporter
            command:
              - /export
              - --name=scheduled_autoscaler
              - --value=35
          restartPolicy: OnFailure
      backoffLimit: 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekends-nonfin-pods-scale-up
spec:
  schedule: "0 14 * * 6,0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: custom-metric-extporter
            image: asia-south1-docker.pkg.dev/icici-terraform-svc-now/gke-scheduled-autoscaler/custom-metric-exporter
            command:
              - /export
              - --name=scheduled_autoscaler
              - --value=40
          restartPolicy: OnFailure
      backoffLimit: 1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: weekends-nonfin-pods-scale-down
spec:
  schedule: "0 0 * * 6,0"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: custom-metric-extporter
            image: asia-south1-docker.pkg.dev/icici-terraform-svc-now/gke-scheduled-autoscaler/custom-metric-exporter
            command:
              - /export
              - --name=scheduled_autoscaler
              - --value=20
          restartPolicy: OnFailure
      backoffLimit: 1
---